/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Gustavo Milanez
 */
public class Matricula extends javax.swing.JFrame {

    /**
     * Creates new form Matricula
     */
    public Matricula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbMan = new javax.swing.JCheckBox();
        jcbTar = new javax.swing.JCheckBox();
        jcbNoi = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rdoTecno = new javax.swing.JRadioButton();
        rdoTec = new javax.swing.JRadioButton();
        jcbUni = new javax.swing.JComboBox<>();
        btnMat = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        lblNom = new javax.swing.JLabel();
        lblCur = new javax.swing.JLabel();
        lblTur = new javax.swing.JLabel();
        lblUni = new javax.swing.JLabel();

        rdoTec = new javax.swing.JRadioButton();
        rdoTecno = new javax.swing.JRadioButton();

        buttonGroup1.add(rdoTec);
        buttonGroup1.add(rdoTecno);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Matrícula");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Curso:");

        jcbMan.setText("Manhã");
        jcbMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbManActionPerformed(evt);
            }
        });

        jcbTar.setText("Tarde");
        jcbTar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTarActionPerformed(evt);
            }
        });

        jcbNoi.setText("Noite");
        jcbNoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbNoiActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Turno:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Unidade:");

        rdoTecno.setText("Tecnólogo");
        rdoTecno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoTecnoActionPerformed(evt);
            }
        });

        rdoTec.setText("Técnico");
        rdoTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoTecActionPerformed(evt);
            }
        });

        jcbUni.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione>", "Senac Centro", "Senac Portão" }));
        jcbUni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbUniActionPerformed(evt);
            }
        });

        btnMat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMat.setText("Matricular");
        btnMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 0, 51));
        btnExit.setText("X");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblResult.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblResult.setText("Confira sua matrícula");

        lblNom.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNom.setText("Nome:");

        lblCur.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCur.setText("Curso:");

        lblTur.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTur.setText("Turno:");

        lblUni.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUni.setText("Unidade:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExit)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnMat, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbMan)
                    .addComponent(jcbTar)
                    .addComponent(jcbNoi)
                    .addComponent(jLabel5)
                    .addComponent(jcbUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdoTec)
                                .addGap(18, 18, 18)
                                .addComponent(rdoTecno))
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(189, 189, 189)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResult)
                            .addComponent(lblUni)
                            .addComponent(lblTur)
                            .addComponent(lblCur)
                            .addComponent(lblNom))))
                .addContainerGap(259, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnExit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblResult))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rdoTec)
                                    .addComponent(rdoTecno))
                                .addGap(12, 12, 12)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblTur)
                                .addGap(18, 18, 18)
                                .addComponent(lblUni)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbMan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbTar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbNoi)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnMat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        lblResult.setVisible(false);
        lblNom.setVisible(false);
        lblCur.setVisible(false);
        lblTur.setVisible(false);
        lblUni.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbTarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTarActionPerformed
        if(jcbTar.isSelected()){
            jcbMan.setEnabled(false);
            jcbNoi.setEnabled(false);
        }else{
            jcbMan.setEnabled(true);
            jcbNoi.setEnabled(true);
        }
    }//GEN-LAST:event_jcbTarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void jcbManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbManActionPerformed
        if(jcbMan.isSelected()){
            jcbTar.setEnabled(false);
            jcbNoi.setEnabled(false);
        }else{
            jcbTar.setEnabled(true);
            jcbNoi.setEnabled(true);
        }
    }//GEN-LAST:event_jcbManActionPerformed

    private void jcbNoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbNoiActionPerformed
        if(jcbNoi.isSelected()){
            jcbTar.setEnabled(false);
            jcbMan.setEnabled(false);
        }else{
            jcbTar.setEnabled(true);
            jcbMan.setEnabled(true);
        }
    }//GEN-LAST:event_jcbNoiActionPerformed

    private void rdoTecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoTecActionPerformed
        
    }//GEN-LAST:event_rdoTecActionPerformed

    private void rdoTecnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoTecnoActionPerformed
        
    }//GEN-LAST:event_rdoTecnoActionPerformed

    private void jcbUniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbUniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbUniActionPerformed

    private void btnMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatActionPerformed
        String nome = txtNome.getText();
        String unidade = jcbUni.getSelectedItem().toString();
        String curso = null, turno = null;
        
        if(nome.isBlank()){
            nome = "Não informado";
        }
        
        if(rdoTec.isSelected()){
            curso = "Técnico";
        }else if(rdoTecno.isSelected()){
            curso = "Tecnólogo";
        }else{
            curso = "Não selecionado";
        }
        
        if(jcbMan.isSelected()){
            turno = "Manhã";
        }else if(jcbTar.isSelected()){
            turno = "Tarde";
        }else if(jcbNoi.isSelected()){
            turno = "Noite";
        }else{
            turno = "Não selecionado";
        }
        
        if(unidade.equals("<Selecione>")){
            unidade = "Não selecionado";
        }
        
        lblResult.setVisible(true);
        lblNom.setVisible(true);
        lblCur.setVisible(true);
        lblTur.setVisible(true);
        lblUni.setVisible(true);
        
        lblNom.setText("Nome:   "+nome);
        lblCur.setText("Curso:   "+curso);
        lblTur.setText("Turno:   "+turno);
        lblUni.setText("Unidade:   "+unidade);
    }//GEN-LAST:event_btnMatActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Matricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Matricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Matricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Matricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Matricula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnMat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JCheckBox jcbMan;
    private javax.swing.JCheckBox jcbNoi;
    private javax.swing.JCheckBox jcbTar;
    private javax.swing.JComboBox<String> jcbUni;
    private javax.swing.JLabel lblCur;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblTur;
    private javax.swing.JLabel lblUni;
    private javax.swing.JRadioButton rdoTec;
    private javax.swing.JRadioButton rdoTecno;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
