
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Gustavo Milanez
 */
public class editorTexto extends javax.swing.JFrame {

    /**
     * Creates new form editorTexto
     */
    public editorTexto() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtaTxt = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmiSai = new javax.swing.JMenu();
        jmiNov = new javax.swing.JMenuItem();
        jmiAbr = new javax.swing.JMenuItem();
        jmiSal = new javax.swing.JMenuItem();
        jmiSalCom = new javax.swing.JMenuItem();
        jmiSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtaTxt.setColumns(20);
        jtaTxt.setRows(5);
        jScrollPane1.setViewportView(jtaTxt);

        jmiSai.setText("Arquivo");

        jmiNov.setText("Novo");
        jmiNov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNovActionPerformed(evt);
            }
        });
        jmiSai.add(jmiNov);

        jmiAbr.setText("Abrir");
        jmiAbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAbrActionPerformed(evt);
            }
        });
        jmiSai.add(jmiAbr);

        jmiSal.setText("Salvar");
        jmiSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalActionPerformed(evt);
            }
        });
        jmiSai.add(jmiSal);

        jmiSalCom.setText("Salvar como");
        jmiSalCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalComActionPerformed(evt);
            }
        });
        jmiSai.add(jmiSalCom);

        jmiSair.setText("Sair");
        jmiSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSairActionPerformed(evt);
            }
        });
        jmiSai.add(jmiSair);

        jMenuBar1.add(jmiSai);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiNovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNovActionPerformed
        jtaTxt.setText("");
    }//GEN-LAST:event_jmiNovActionPerformed

    private void jmiAbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAbrActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setDialogTitle("Abrir");
        fc.showOpenDialog(this);
        File f = fc.getSelectedFile();
        
        try (BufferedReader reader = new BufferedReader(new FileReader(f))) {
            jtaTxt.setText("");
            String line;
            while ((line = reader.readLine()) != null) {
                jtaTxt.append(line);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Erro ao ler o arquivo: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jmiAbrActionPerformed

    private void jmiSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalActionPerformed
        String texto = jtaTxt.getText();

        try (FileWriter writer = new FileWriter("texto_salvo.txt", false)) {
            writer.write(texto);
            JOptionPane.showMessageDialog(this, "Texto salvo com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        }catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar o texto: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jmiSalActionPerformed

    private void jmiSalComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalComActionPerformed
        JFileChooser f = new JFileChooser();
        f.setDialogTitle("Salvar como");
        int result = f.showSaveDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File fileToSave = f.getSelectedFile();
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(fileToSave))) {
                writer.write(jtaTxt.getText());
                JOptionPane.showMessageDialog(this, "Arquivo salvo com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Erro ao salvar o arquivo: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jmiSalComActionPerformed

    private void jmiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmiSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editorTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editorTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editorTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editorTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editorTexto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem jmiAbr;
    private javax.swing.JMenuItem jmiNov;
    private javax.swing.JMenu jmiSai;
    private javax.swing.JMenuItem jmiSair;
    private javax.swing.JMenuItem jmiSal;
    private javax.swing.JMenuItem jmiSalCom;
    private javax.swing.JTextArea jtaTxt;
    // End of variables declaration//GEN-END:variables
}
